from enum import Enum


class ROLE(Enum):
    AFILIADO = 'AFILIADO'
    SUBAFILIADO = 'SUBAFILIADO'
    INFLUENCER = 'INFLUENCER'
    EMBAIXADOR = 'EMBAIXADOR'
    OPERADOR = 'OPERADOR'
    ADMIN = 'ADMIN'